// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package schema

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type ChangePasswordInput struct {
	CurrentPassword string `json:"currentPassword"`
	NewPassword     string `json:"newPassword"`
}

type CreateUserInput struct {
	Username    string       `json:"username"`
	DisplayName string       `json:"displayName"`
	Roles       []Role       `json:"roles,omitempty"`
	Permissions []Permission `json:"permissions,omitempty"`
	Rank        int          `json:"rank"`
}

type LoginInput struct {
	Username          string `json:"username"`
	Password          string `json:"password"`
	SessionTTLSeconds int    `json:"sessionTtlSeconds"`
}

type Mutation struct {
}

type PageInfo struct {
	// Opaque and stable. Only valid with the same `filter` and `sortBy`.
	EndCursor   *string `json:"endCursor,omitempty"`
	HasNextPage bool    `json:"hasNextPage"`
}

type PasswordResetInfo struct {
	Username string `json:"username"`
	// 15 minutes from issue.
	ExpiresAt time.Time `json:"expiresAt"`
}

// Client-defined and opaque to the server, which stores and returns it
// unchanged.
type Preference struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Query struct {
}

// Server-side authentication state.
type Session struct {
	ID            string    `json:"id"`
	LastUserAgent *string   `json:"lastUserAgent,omitempty"`
	Current       bool      `json:"current"`
	LastIPAddress *string   `json:"lastIpAddress,omitempty"`
	CreatedAt     time.Time `json:"createdAt"`
	// Set whenever a request carries the session id.
	LastUsedAt time.Time `json:"lastUsedAt"`
	// Sliding: extended by a full term on any use in the last third.
	ExpiresAt time.Time `json:"expiresAt"`
	// When step-up lapses, 30 minutes from the last password proved. `null` when
	// the session is not raised.
	StepUpExpiresAt *time.Time `json:"stepUpExpiresAt,omitempty"`
	// `null` while live. Once set, the session is over whatever `expiresAt` says.
	EndedAt *time.Time `json:"endedAt,omitempty"`
}

type SessionFilterInput struct {
	// `true` finds the live ones, `false` the ended.
	Live *bool `json:"live,omitempty"`
	// Case-insensitive substring of `lastUserAgent`.
	UserAgent     *string    `json:"userAgent,omitempty"`
	CreatedAfter  *time.Time `json:"createdAfter,omitempty"`
	CreatedBefore *time.Time `json:"createdBefore,omitempty"`
	EndedAfter    *time.Time `json:"endedAfter,omitempty"`
	EndedBefore   *time.Time `json:"endedBefore,omitempty"`
}

type SetPasswordInput struct {
	Password          string `json:"password"`
	SessionTTLSeconds int    `json:"sessionTtlSeconds"`
}

type SetPreferenceInput struct {
	// `null` removes the key.
	Value *string `json:"value,omitempty"`
}

type SetUserPermissionsInput struct {
	Permissions []Permission `json:"permissions"`
}

type SetUserRankInput struct {
	Rank int `json:"rank"`
}

type SetUserRolesInput struct {
	Roles []Role `json:"roles"`
}

type SetupInput struct {
	Username          string `json:"username"`
	DisplayName       string `json:"displayName"`
	Password          string `json:"password"`
	SessionTTLSeconds int    `json:"sessionTtlSeconds"`
}

type StepUpInput struct {
	Password string `json:"password"`
}

// Subscriptions run over a WebSocket, subprotocol `graphql-transport-ws`. The
// session cookie travels on the handshake, which is an ordinary HTTP request,
// and the browser sends it by itself. Nothing authenticates inside the socket.
//
// A field here emits once on subscribe, carrying the state at that moment, and
// again on each change. So a client needs no query to start from, and a first
// event does not mean something changed.
//
// A subscription ends as soon as access changes: any revocation, or any change
// of permissions, closes every subscription on that session. The stream just
// completes, with no error. Subscribe again. If the session is gone, that
// attempt fails. A session that expires under a live socket closes the socket
// itself, with code `4403`.
//
// One socket is enough for a client, and a socket is limited: 50 subscriptions
// at once (another fails with `LIMIT_REACHED`), and operations started no faster
// than 10 a second (faster ones fail with `RATE_LIMITED`). One address holds at
// most 20 sockets; the handshake of another is refused with `429`.
type Subscription struct {
}

// At least one value required.
type UpdateProfileInput struct {
	DisplayName *string `json:"displayName,omitempty"`
}

type User struct {
	ID          string `json:"id"`
	Username    string `json:"username"`
	DisplayName string `json:"displayName"`
	// A user acts only on lower ranks, and assigns no rank but a lower one.
	Rank              int          `json:"rank"`
	Roles             []Role       `json:"roles"`
	DirectPermissions []Permission `json:"directPermissions"`
	// Direct plus roles.
	Permissions []Permission `json:"permissions"`
	// `null` when a password was never set, or once `resetUserCredentials` cleared
	// it. `setPassword` fills it.
	PasswordSetAt *time.Time `json:"passwordSetAt,omitempty"`
	CreatedAt     time.Time  `json:"createdAt"`
}

type UserFilterInput struct {
	// Case-insensitive substring of `username` or `displayName`.
	Search *string `json:"search,omitempty"`
	Role   *Role   `json:"role,omitempty"`
	// `false` finds those who have yet to finish a first sign-in.
	HasPassword   *bool      `json:"hasPassword,omitempty"`
	CreatedAfter  *time.Time `json:"createdAfter,omitempty"`
	CreatedBefore *time.Time `json:"createdBefore,omitempty"`
}

type UserPage struct {
	Items    []*User   `json:"items"`
	PageInfo *PageInfo `json:"pageInfo"`
	// Matching users, not all of them.
	TotalCount int `json:"totalCount"`
}

type Viewer struct {
	User *User `json:"user"`
	// What the current session allows.
	Permissions []Permission  `json:"permissions"`
	Session     *Session      `json:"session"`
	Preferences []*Preference `json:"preferences"`
}

// Failures arrive in the response's `errors`. Their `message` is prose;
// `extensions` states the same failure in terms this schema defines.
//
// - `path` — the field that failed
// - `extensions.code` — one of these values
//
// Fields built on this base fail the same way:
//
// ```graphql
//
//	query {
//	  droids(filter: { manufacturedBefore: "long ago" }) {
//	    name
//	  }
//	}
//
// ```
//
// ```json
//
//	{
//	  "errors": [
//	    {
//	      "message": "manufacturedBefore is not a date",
//	      "path": ["droids"],
//	      "extensions": {
//	        "code": "INVALID_INPUT",
//	        "inputPath": ["filter", "manufacturedBefore"],
//	        "reason": "MALFORMED"
//	      }
//	    }
//	  ]
//	}
//
// ```
type ErrorCode string

const (
	// Validation stops at the first bad argument and throws. Where an argument is
	// at fault, `extensions.inputPath` names it, outermost first.
	ErrorCodeInvalidInput    ErrorCode = "INVALID_INPUT"
	ErrorCodeInternal        ErrorCode = "INTERNAL"
	ErrorCodeUnauthenticated ErrorCode = "UNAUTHENTICATED"
	// Call `stepUp`, then retry unchanged.
	ErrorCodeStepUpRequired ErrorCode = "STEP_UP_REQUIRED"
	ErrorCodeAccessDenied   ErrorCode = "ACCESS_DENIED"
	// A cap is full.
	ErrorCodeLimitReached ErrorCode = "LIMIT_REACHED"
	// Too many attempts too quickly. `extensions.retryAfterSeconds` says when the
	// next one will be let through.
	ErrorCodeRateLimited ErrorCode = "RATE_LIMITED"
)

var AllErrorCode = []ErrorCode{
	ErrorCodeInvalidInput,
	ErrorCodeInternal,
	ErrorCodeUnauthenticated,
	ErrorCodeStepUpRequired,
	ErrorCodeAccessDenied,
	ErrorCodeLimitReached,
	ErrorCodeRateLimited,
}

func (e ErrorCode) IsValid() bool {
	switch e {
	case ErrorCodeInvalidInput, ErrorCodeInternal, ErrorCodeUnauthenticated, ErrorCodeStepUpRequired, ErrorCodeAccessDenied, ErrorCodeLimitReached, ErrorCodeRateLimited:
		return true
	}
	return false
}

func (e ErrorCode) String() string {
	return string(e)
}

func (e *ErrorCode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ErrorCode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ErrorCode", str)
	}
	return nil
}

func (e ErrorCode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ErrorCode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ErrorCode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Why an argument was rejected, in `extensions.reason`.
type InvalidInputReason string

const (
	InvalidInputReasonMalformed    InvalidInputReason = "MALFORMED"
	InvalidInputReasonTooShort     InvalidInputReason = "TOO_SHORT"
	InvalidInputReasonTooLong      InvalidInputReason = "TOO_LONG"
	InvalidInputReasonTooGuessable InvalidInputReason = "TOO_GUESSABLE"
	InvalidInputReasonOutOfRange   InvalidInputReason = "OUT_OF_RANGE"
	InvalidInputReasonTaken        InvalidInputReason = "TAKEN"
	// The view is stale.
	InvalidInputReasonTargetMissing InvalidInputReason = "TARGET_MISSING"
)

var AllInvalidInputReason = []InvalidInputReason{
	InvalidInputReasonMalformed,
	InvalidInputReasonTooShort,
	InvalidInputReasonTooLong,
	InvalidInputReasonTooGuessable,
	InvalidInputReasonOutOfRange,
	InvalidInputReasonTaken,
	InvalidInputReasonTargetMissing,
}

func (e InvalidInputReason) IsValid() bool {
	switch e {
	case InvalidInputReasonMalformed, InvalidInputReasonTooShort, InvalidInputReasonTooLong, InvalidInputReasonTooGuessable, InvalidInputReasonOutOfRange, InvalidInputReasonTaken, InvalidInputReasonTargetMissing:
		return true
	}
	return false
}

func (e InvalidInputReason) String() string {
	return string(e)
}

func (e *InvalidInputReason) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = InvalidInputReason(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid InvalidInputReason", str)
	}
	return nil
}

func (e InvalidInputReason) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *InvalidInputReason) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e InvalidInputReason) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Permission string

const (
	PermissionUserManage Permission = "USER_MANAGE"
)

var AllPermission = []Permission{
	PermissionUserManage,
}

func (e Permission) IsValid() bool {
	switch e {
	case PermissionUserManage:
		return true
	}
	return false
}

func (e Permission) String() string {
	return string(e)
}

func (e *Permission) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Permission(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Permission", str)
	}
	return nil
}

func (e Permission) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Permission) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Permission) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Role string

const (
	// Grants `USER_MANAGE`.
	RoleAdmin Role = "ADMIN"
)

var AllRole = []Role{
	RoleAdmin,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleAdmin:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Role) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Role) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SessionSort string

const (
	SessionSortCreatedDesc  SessionSort = "CREATED_DESC"
	SessionSortCreatedAsc   SessionSort = "CREATED_ASC"
	SessionSortLastUsedDesc SessionSort = "LAST_USED_DESC"
	SessionSortLastUsedAsc  SessionSort = "LAST_USED_ASC"
	SessionSortEndedDesc    SessionSort = "ENDED_DESC"
	SessionSortEndedAsc     SessionSort = "ENDED_ASC"
)

var AllSessionSort = []SessionSort{
	SessionSortCreatedDesc,
	SessionSortCreatedAsc,
	SessionSortLastUsedDesc,
	SessionSortLastUsedAsc,
	SessionSortEndedDesc,
	SessionSortEndedAsc,
}

func (e SessionSort) IsValid() bool {
	switch e {
	case SessionSortCreatedDesc, SessionSortCreatedAsc, SessionSortLastUsedDesc, SessionSortLastUsedAsc, SessionSortEndedDesc, SessionSortEndedAsc:
		return true
	}
	return false
}

func (e SessionSort) String() string {
	return string(e)
}

func (e *SessionSort) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SessionSort(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SessionSort", str)
	}
	return nil
}

func (e SessionSort) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SessionSort) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SessionSort) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type UserSort string

const (
	UserSortCreatedDesc  UserSort = "CREATED_DESC"
	UserSortCreatedAsc   UserSort = "CREATED_ASC"
	UserSortUsernameAsc  UserSort = "USERNAME_ASC"
	UserSortUsernameDesc UserSort = "USERNAME_DESC"
	UserSortRankDesc     UserSort = "RANK_DESC"
	UserSortRankAsc      UserSort = "RANK_ASC"
)

var AllUserSort = []UserSort{
	UserSortCreatedDesc,
	UserSortCreatedAsc,
	UserSortUsernameAsc,
	UserSortUsernameDesc,
	UserSortRankDesc,
	UserSortRankAsc,
}

func (e UserSort) IsValid() bool {
	switch e {
	case UserSortCreatedDesc, UserSortCreatedAsc, UserSortUsernameAsc, UserSortUsernameDesc, UserSortRankDesc, UserSortRankAsc:
		return true
	}
	return false
}

func (e UserSort) String() string {
	return string(e)
}

func (e *UserSort) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserSort(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserSort", str)
	}
	return nil
}

func (e UserSort) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserSort) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserSort) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
