package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"control/internal/schema"
)

// Setup is the resolver for the setup field.
func (r *mutationResolver) Setup(ctx context.Context, input schema.SetupInput) (*schema.Viewer, error) {
	return r.Accounts.Setup(ctx, input)
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input schema.LoginInput) (*schema.Viewer, error) {
	return r.Accounts.Login(ctx, input)
}

// RequestPasswordReset is the resolver for the requestPasswordReset field.
func (r *mutationResolver) RequestPasswordReset(ctx context.Context, username string) (*schema.Void, error) {
	return r.Accounts.RequestPasswordReset(ctx, username)
}

// SetPassword is the resolver for the setPassword field.
func (r *mutationResolver) SetPassword(ctx context.Context, secret string, input schema.SetPasswordInput) (*schema.Viewer, error) {
	return r.Accounts.SetPassword(ctx, secret, input)
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (*schema.Void, error) {
	return r.Accounts.Logout(ctx)
}

// StepUp is the resolver for the stepUp field.
func (r *mutationResolver) StepUp(ctx context.Context, input schema.StepUpInput) (*schema.Viewer, error) {
	return r.Accounts.StepUp(ctx, input)
}

// ChangePassword is the resolver for the changePassword field.
func (r *mutationResolver) ChangePassword(ctx context.Context, input schema.ChangePasswordInput) (*schema.Viewer, error) {
	return r.Accounts.ChangePassword(ctx, input)
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input schema.UpdateProfileInput) (*schema.Viewer, error) {
	return r.Accounts.UpdateProfile(ctx, input)
}

// SetPreference is the resolver for the setPreference field.
func (r *mutationResolver) SetPreference(ctx context.Context, key string, input schema.SetPreferenceInput) ([]*schema.Preference, error) {
	return r.Accounts.SetPreference(ctx, key, input)
}

// RevokeSession is the resolver for the revokeSession field.
func (r *mutationResolver) RevokeSession(ctx context.Context, sessionID string) ([]*schema.Session, error) {
	return r.Accounts.RevokeSession(ctx, sessionID)
}

// RevokeOtherSessions is the resolver for the revokeOtherSessions field.
func (r *mutationResolver) RevokeOtherSessions(ctx context.Context) ([]*schema.Session, error) {
	return r.Accounts.RevokeOtherSessions(ctx)
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input schema.CreateUserInput) (*schema.User, error) {
	return r.Accounts.CreateUser(ctx, input)
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, userID string) (*schema.Void, error) {
	return r.Accounts.DeleteUser(ctx, userID)
}

// ResetUserCredentials is the resolver for the resetUserCredentials field.
func (r *mutationResolver) ResetUserCredentials(ctx context.Context, userID string) (*schema.User, error) {
	return r.Accounts.ResetUserCredentials(ctx, userID)
}

// SetUserRoles is the resolver for the setUserRoles field.
func (r *mutationResolver) SetUserRoles(ctx context.Context, userID string, input schema.SetUserRolesInput) (*schema.User, error) {
	return r.Accounts.SetUserRoles(ctx, userID, input)
}

// SetUserPermissions is the resolver for the setUserPermissions field.
func (r *mutationResolver) SetUserPermissions(ctx context.Context, userID string, input schema.SetUserPermissionsInput) (*schema.User, error) {
	return r.Accounts.SetUserPermissions(ctx, userID, input)
}

// SetUserRank is the resolver for the setUserRank field.
func (r *mutationResolver) SetUserRank(ctx context.Context, userID string, input schema.SetUserRankInput) (*schema.User, error) {
	return r.Accounts.SetUserRank(ctx, userID, input)
}

// SetupRequired is the resolver for the setupRequired field.
func (r *queryResolver) SetupRequired(ctx context.Context) (bool, error) {
	return r.Accounts.SetupRequired(ctx)
}

// PasswordResetInfo is the resolver for the passwordResetInfo field.
func (r *queryResolver) PasswordResetInfo(ctx context.Context, secret string) (*schema.PasswordResetInfo, error) {
	return r.Accounts.PasswordResetInfo(ctx, secret)
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*schema.Viewer, error) {
	return r.Accounts.Me(ctx)
}

// Sessions is the resolver for the sessions field.
func (r *queryResolver) Sessions(ctx context.Context, filter *schema.SessionFilterInput, sortBy *schema.SessionSort, limit int) ([]*schema.Session, error) {
	return r.Accounts.Sessions(ctx, filter, sortBy, limit)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, filter *schema.UserFilterInput, sortBy *schema.UserSort, after *string, limit int) (*schema.UserPage, error) {
	return r.Accounts.Users(ctx, filter, sortBy, after, limit)
}

// Me is the resolver for the me field.
func (r *subscriptionResolver) Me(ctx context.Context) (<-chan *schema.Viewer, error) {
	return r.Accounts.SubscribeViewer(ctx)
}

// Sessions is the resolver for the sessions field.
func (r *subscriptionResolver) Sessions(ctx context.Context, filter *schema.SessionFilterInput, sortBy *schema.SessionSort, limit int) (<-chan []*schema.Session, error) {
	return r.Accounts.SubscribeSessions(ctx, filter, sortBy, limit)
}

// UsersChanged is the resolver for the usersChanged field.
func (r *subscriptionResolver) UsersChanged(ctx context.Context) (<-chan *schema.Void, error) {
	return r.Accounts.SubscribeUsersChanged(ctx)
}
